language: python
sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get install -y postgresql-9.3-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
script: true
notifications:
  email: false
